# =============================================================================
# ENTERPRISE GRADE ANALYSIS OPTIONS
# =============================================================================
# Standard: Strict/Secure
# Enforced by: Antigravity Agent
# =============================================================================

include: package:flutter_lints/flutter.yaml

analyzer:
  # Strict language settings
  language:
    # strict-casts: true # TODO: Enable strict-casts for stricter type checking
    # strict-inference: true # TODO: Enable strict-inference for stricter type checking
    # strict-raw-types: true # TODO: Enable strict-raw-types for better type safety

  # Exclude generated files from analysis
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/*.config.dart"
    - "**/*.gr.dart"
    - "test/.test_coverage.dart"
    - "lib/generated_plugin_registrant.dart"

  errors:
    # Treat missing required parameters as errors
    missing_required_param: error
    # Treat missing return values as errors
    missing_return: error
    # Allow TODOs without warnings (for development)
    todo: ignore
    # Treat invalid assignments as errors
    invalid_assignment: error
    # Treat dead code as info (less intrusive than warning)
    dead_code: info

linter:
  rules:
    # -------------------------------------------------------------------------
    # ERROR PREVENTION & TYPE SAFETY
    # -------------------------------------------------------------------------
    - always_declare_return_types
    # always_require_non_null_named_parameters — removed in Dart 3.3.0
    - annotate_overrides
    - avoid_empty_else
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - hash_and_equals
    - implementation_imports
    - collection_methods_unrelated_type
    - no_duplicate_case_values
    - no_logic_in_create_state
    - non_constant_identifier_names
    - null_closures
    - overridden_fields
    - package_names
    - prefer_void_to_null
    - recursive_getters
    - test_types_in_equals
    - throw_in_finally
    - type_init_formals
    - unnecessary_null_in_if_null_operators
    - unrelated_type_equality_checks
    - use_build_context_synchronously
    - use_rethrow_when_possible
    - valid_regexps
    - void_checks

    # -------------------------------------------------------------------------
    # STYLE & READABILITY
    # -------------------------------------------------------------------------
    # - always_put_control_body_on_new_line # TODO: Enable for stricter style
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses # TODO: Enable and fix specific exceptions
    - avoid_catching_errors
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_field_initializers_in_const_classes
    - avoid_function_literals_in_foreach_calls
    - avoid_implementing_value_types
    - avoid_js_rounded_ints
    - avoid_multiple_declarations_per_line
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_void
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - file_names
    - library_names
    - library_prefixes
    # list_remove_unrelated_type — removed in Dart 3.3.0 (replaced by collection_methods_unrelated_type)
    - no_adjacent_strings_in_list
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - one_member_abstracts
    - only_throw_errors
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_adjacent_string_concatenation
    - prefer_asserts_in_initializer_lists
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_int_literals
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - sized_box_for_whitespace
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_late
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_is_even_rather_than_modulo
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_setters_to_change_properties
    - use_string_buffers
    - use_super_parameters
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
