// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYZdooWqBuBH3EQLS5MPnp3wrwFboIlaM',
    appId: '1:1058815487233:web:5304c2e3cf81753405bf00',
    messagingSenderId: '1058815487233',
    projectId: 'guardiancare-8a5e4',
    authDomain: 'guardiancare-8a5e4.firebaseapp.com',
    storageBucket: 'guardiancare-8a5e4.appspot.com',
    measurementId: 'G-CEXTNDHP65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8-vuMD81DFdg9siyZXgwqT8XwV9StcNk',
    appId: '1:1058815487233:android:678add568111b3ad05bf00',
    messagingSenderId: '1058815487233',
    projectId: 'guardiancare-8a5e4',
    storageBucket: 'guardiancare-8a5e4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZP0ZeZ32_8eJL0Jc023kmhWj14nPypPg',
    appId: '1:1058815487233:ios:63a30cd3b4b9f78305bf00',
    messagingSenderId: '1058815487233',
    projectId: 'guardiancare-8a5e4',
    storageBucket: 'guardiancare-8a5e4.appspot.com',
    androidClientId: '1058815487233-no73hf8uagkvu31ekqd02p32ruf9nibj.apps.googleusercontent.com',
    iosClientId: '1058815487233-anftiq3ec9un1ufiupkkm8esbrbet3kq.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZP0ZeZ32_8eJL0Jc023kmhWj14nPypPg',
    appId: '1:1058815487233:ios:0d4880e106f623cc05bf00',
    messagingSenderId: '1058815487233',
    projectId: 'guardiancare-8a5e4',
    storageBucket: 'guardiancare-8a5e4.appspot.com',
    androidClientId: '1058815487233-no73hf8uagkvu31ekqd02p32ruf9nibj.apps.googleusercontent.com',
    iosClientId: '1058815487233-jthbeul3o4mcf0jhkvd8o27k7ura811l.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp.RunnerTests',
  );
}
