// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJKvh4ZXb3npq8cL9-mk-kDlSIUO6VppU',
    appId: '1:331315801686:web:2a2609fb7d0ec4187595f7',
    messagingSenderId: '331315801686',
    projectId: 'guardiancare-a210f',
    authDomain: 'guardiancare-a210f.firebaseapp.com',
    databaseURL: 'https://guardiancare-a210f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'guardiancare-a210f.appspot.com',
    measurementId: 'G-HRJ3C6VEXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiK-huaMXXmnI4M0LxYNtH5NasP1o1iHQ',
    appId: '1:331315801686:android:bbc3124e1812cc917595f7',
    messagingSenderId: '331315801686',
    projectId: 'guardiancare-a210f',
    databaseURL: 'https://guardiancare-a210f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'guardiancare-a210f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwCbSP-Qw1bRg5BvVco5x0VqxoBMAtLgs',
    appId: '1:331315801686:ios:c956a1fa41d7bbb47595f7',
    messagingSenderId: '331315801686',
    projectId: 'guardiancare-a210f',
    databaseURL: 'https://guardiancare-a210f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'guardiancare-a210f.appspot.com',
    androidClientId: '331315801686-01tinu5ukqe35u4ivvn3fqo4ju59pp1d.apps.googleusercontent.com',
    iosClientId: '331315801686-a0u07tpvqes8eu000e1iclahjmsqg1ss.apps.googleusercontent.com',
    iosBundleId: 'app.guardiancare.guardianscare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwCbSP-Qw1bRg5BvVco5x0VqxoBMAtLgs',
    appId: '1:331315801686:ios:c956a1fa41d7bbb47595f7',
    messagingSenderId: '331315801686',
    projectId: 'guardiancare-a210f',
    databaseURL: 'https://guardiancare-a210f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'guardiancare-a210f.appspot.com',
    androidClientId: '331315801686-01tinu5ukqe35u4ivvn3fqo4ju59pp1d.apps.googleusercontent.com',
    iosClientId: '331315801686-a0u07tpvqes8eu000e1iclahjmsqg1ss.apps.googleusercontent.com',
    iosBundleId: 'app.guardiancare.guardianscare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJKvh4ZXb3npq8cL9-mk-kDlSIUO6VppU',
    appId: '1:331315801686:web:942094b5fc96fe447595f7',
    messagingSenderId: '331315801686',
    projectId: 'guardiancare-a210f',
    authDomain: 'guardiancare-a210f.firebaseapp.com',
    databaseURL: 'https://guardiancare-a210f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'guardiancare-a210f.appspot.com',
    measurementId: 'G-SEF3D98352',
  );

}