import 'dart:convert';
import 'package:dartz/dartz.dart';
import 'package:equatable/equatable.dart';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import 'package:guardiancare/core/constants/constants.dart';
import 'package:guardiancare/core/error/failures.dart';

/// Data class representing video information from YouTube API
/// 
/// Requirements: 4.2
class VideoData extends Equatable {
  final String videoId;
  final String title;
  final String thumbnailUrl;
  final String videoUrl;

  const VideoData({
    required this.videoId,
    required this.title,
    required this.thumbnailUrl,
    required this.videoUrl,
  });

  /// Creates a [VideoData] from YouTube API response
  factory VideoData.fromYoutubeResponse(Map<String, dynamic> item) {
    final videoId = item['id']['videoId'] as String;
    final snippet = item['snippet'] as Map<String, dynamic>;
    final title = snippet['title'] as String;
    final thumbnails = snippet['thumbnails'] as Map<String, dynamic>;
    final highThumbnail = thumbnails['high'] as Map<String, dynamic>;
    final thumbnailUrl = highThumbnail['url'] as String;

    return VideoData(
      videoId: videoId,
      title: title,
      thumbnailUrl: thumbnailUrl,
      videoUrl: 'https://youtu.be/$videoId',
    );
  }

  @override
  List<Object> get props => [videoId, title, thumbnailUrl, videoUrl];
}

/// Service that handles YouTube API interactions exclusively
/// 
/// This service is responsible for searching YouTube videos
/// based on search terms generated by GeminiAIService.
/// 
/// Requirements: 4.2
abstract class YoutubeSearchService {
  /// Searches for a video on YouTube using the given search term
  /// 
  /// Returns [Either<Failure, VideoData>] containing:
  /// - [Right] with [VideoData] on success
  /// - [Left] with [YoutubeApiFailure] on error
  Future<Either<Failure, VideoData>> searchVideo(String term);
}

/// Implementation of [YoutubeSearchService] using YouTube Data API v3
class YoutubeSearchServiceImpl implements YoutubeSearchService {
  final http.Client _httpClient;
  final String _apiKey;

  /// Creates a [YoutubeSearchServiceImpl]
  /// 
  /// [httpClient] - HTTP client for making API requests (optional, defaults to new client)
  /// [apiKey] - YouTube API key (optional, defaults to kYoutubeApiKey)
  YoutubeSearchServiceImpl({
    http.Client? httpClient,
    String? apiKey,
  })  : _httpClient = httpClient ?? http.Client(),
        _apiKey = apiKey ?? kYoutubeApiKey;

  @override
  Future<Either<Failure, VideoData>> searchVideo(String term) async {
    if (term.isEmpty) {
      return const Left(YoutubeApiFailure('Search term cannot be empty'));
    }

    // Skip invalid terms that start with dash
    if (term.startsWith('-')) {
      return const Left(YoutubeApiFailure('Invalid search term format'));
    }

    try {
      final formattedTerm = term.trim();
      debugPrint('🔍 YouTube API: Searching for "$formattedTerm"');
      
      final url = Uri.parse(
        'https://www.googleapis.com/youtube/v3/search'
        '?part=snippet'
        '&q=${Uri.encodeComponent(formattedTerm)}'
        '&maxResults=1'
        '&type=video'
        '&key=$_apiKey',
      );

      final response = await _httpClient.get(url);

      if (response.statusCode != 200) {
        debugPrint('❌ YouTube API error: Status ${response.statusCode}');
        debugPrint('   Response: ${response.body}');
        return Left(YoutubeApiFailure(
          'YouTube API request failed with status ${response.statusCode}',
          code: response.statusCode.toString(),
        ));
      }

      final jsonData = jsonDecode(response.body) as Map<String, dynamic>;
      final items = jsonData['items'] as List<dynamic>?;

      if (items == null || items.isEmpty) {
        debugPrint('⚠️ YouTube API: No videos found for "$formattedTerm"');
        return Left(YoutubeApiFailure('No videos found for term: $term'));
      }

      final videoData = VideoData.fromYoutubeResponse(
        items.first as Map<String, dynamic>,
      );

      debugPrint('✅ YouTube API: Found video "${videoData.title}"');
      return Right(videoData);
    } catch (e) {
      debugPrint('❌ YouTube API exception: $e');
      return Left(YoutubeApiFailure('YouTube API error: ${e.toString()}'));
    }
  }
}
